# botfather token
token: <bot token as give by BotFather>
# mailman url to parse for getting email info
mailman-url: http://ml.linuxvar.it/pipermail/talking/$Y-$M/date.html
# wheter to use a webserver or polling
webhook: False
webhook-domain: https://example.com/
webhook-path: vargram
webhook-port: 8443
webhook-key: /etc/ssl/private.key
webhook-cert: /etc/ssl/cert.pem
# smtp parameters
smtp-address: smtp.gmail.com
smtp-port: 587
smtp-user: <user-email>
smtp-pass: <user-password>
smtp-to: talking@ml.linuxvar.it
