# botfather token
token: <bot token as give by BotFather>
# mailman url to parse for getting email info
mailman-url: http://ml.linuxvar.it/pipermail/talking/$Y-$M/date.html
# wheter to use a webserver or polling
webhook: null
webhook-port: null
heroku-url: https://vargram-bot.herokuapp.com/
# smtp parameters
smtp-address: smtp.gmail.com
smtp-port: 587
smtp-user: <user-email>
smtp-pass: <user-password>
smtp-to: talking@ml.linuxvar.it
